name: spendly
description: A personal spending assistant app to track, understand, and control your finances.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Firebase (Flutter 3.32 සඳහා නවතම)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Charts
  fl_chart: ^0.70.2

  # Date & Currency formatting
  intl: ^0.20.2

  # Loading indicators
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/Spendly_icon.jpeg
  remove_alpha_ios: true
  adaptive_icon_background: '#07183F'
  adaptive_icon_foreground: assets/Spendly_icon.jpeg
  adaptive_icon_foreground_inset: 0
  web:
    generate: true
    image_path: assets/Spendly_icon.jpeg
    background_color: '#07183F'
    theme_color: '#07183F'

flutter:
  uses-material-design: true