
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkw4BBmN2crRx_osKaHbgAxs31Qq_5QfE',
    authDomain: 'expensetracker-82e2b.firebaseapp.com',
    projectId: 'expensetracker-82e2b',
    storageBucket: 'expensetracker-82e2b.firebasestorage.app',
    messagingSenderId: '252803967430',
    appId: '1:252803967430:web:8b6fc7b7edd95979a4aac7',
    measurementId: 'G-NQPL4B1WPH'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRbq_OuASFe1tfZmjKK5C3-10FQ15730',
    appId: '1:252803967430:android:e2cceb1d41bfccfda4aac7',
    messagingSenderId: '252803967430',
    projectId: 'expensetracker-82e2b',
    storageBucket: 'expensetracker-82e2b.firebasestorage.app'
  );
}
